social_network/newfeed/urls.py
from re import template
from urllib.parse import urlparse
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name ="newfeed"

urlpatterns = [
    path('', views.newfeed, name="newfeed"),
    path('add/', views.add_Post, name="addPost"),
    path('save/', views.save_Post, name="savePost"),
    path('404/', views.error, name='cocl'),
    path('<int:pk>/', views.posts, name='posts'),
]

social_network/social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("newfeed.urls")),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/user/urls.py
from urllib.parse import urlparse
from django.urls import path
from . import views



urlpatterns = [
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register_user'),
    path('logout', views.logout_user, name='logout'),
]

social_network/newfeed/models.py
from distutils.command.upload import upload
from email.mime import image
from email.policy import default
from importlib.metadata import requires
from pyexpat import model
from turtle import title
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_currentuser.middleware import (get_current_user, get_current_authenticated_user) # to get author's name


# create database for post
class Post_content(models.Model):  
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, default=get_current_user)  # create post's author
    content = models.TextField(max_length=10000, blank=False, null=False)  # create content of post
    image = models.ImageField(upload_to = "image", blank=True)  # create a place to store images
    time_create = models.DateTimeField(auto_now_add=True)  # create post time
    
    def __str__(self):
        return self.content
    
    
# create database for comment
class Post_comment(models.Model):
    post = models.ForeignKey(Post_content, on_delete=models.CASCADE)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, default=get_current_user)
    user_comment = models.CharField(max_length=10000, blank=False, null=False)
    image_comment = models.ImageField(upload_to = "comment", blank=True)
    time_comment = models.DateTimeField(auto_now_add=True)
    
    

    
    
    
        
    

social_network/user/models.py
import email
from django.db import models
from django.contrib.auth.models import User


class profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=False, null=False)
    
    def __str__(self):
        return self.email

social_network/newfeed/views.py
from ast import Return
from email.mime import image
import re
from turtle import home
from urllib import request
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.views.generic.edit import CreateView

from .models import Post_content, Post_comment
from .form import PostForm, CommentForm

#show post
def newfeed(request):
    data = {"posts": Post_content.objects.all().order_by('-time_create')}# get all post from database
    return render(request, 'pages/new_feed.html', data)

def posts(request, pk):
    posts = Post_content.objects.filter(pk=pk)
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES, username=request.user, post=posts)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, "pages/posts.html", {"posts": posts, "form": form})
    
#creat post
def add_Post(request):
    if request.user.is_authenticated:
        add = PostForm()
        return render(request, "pages/post.html", { "f": add })  # add value for f = add
    else:
        return render(request, "pages/error.html")

#save post
def save_Post(request):
    if request.method == "POST":    # method="POST" in template
        saveP = PostForm(request.POST, request.FILES)    # create a variable that takes the request containing the attached data and image file
        if saveP.is_valid():  # if the request is valid
            saveP.save()  # save request
            return HttpResponseRedirect('/')   # back to home
        else:
            return render(request, 'pages/404.html')
    else:
        return render(request, 'pages/404.html')
# error   
def error(request):
    return render(request, 'pages/error.html')


# create comment

def post_comment(reuquest):
    if request.user.is_authenticated:
        add_comment = PostForm(commit=False)
        return render(request, "pages/post.html", { "f": add_comment }) 
    else:
        return render(request, "pages/error.html")

# save comment
def save_comment(request):
    if request.method == "POST":
        save_comment = PostForm(request.POST, request.FILES)
        if save_comment.is_valid():
            save_comment.save()
            return HttpResponseRedirect('/')
        else:
            return render(request, 'pages/404.html')
    else:
        return render(request, 'pages/404.html')

# display comment
def display_comment(request):
    cmt = {"cmt": Post_comment.objects.all().order_by("-time_comment")}
    return render(request, 'pages/new_feed.html', cmt)
    

social_network/user/views.py
import email
from multiprocessing import context
import re
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
import newfeed.urls
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .form import RegisterForm
from .models import profile

def login_user(request):
    if request.user.is_authenticated:
        return render(request, "pages/already_login.html", {})
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        
        user = authenticate(request, username=username, password=password)  #get username, password and check check them against each authentication backend
        
        if user is None:   # If the credentials aren’t valid for any backend or if a backend raises PermissionDenied, it returns None
            context = {"error": "Invalid username or password"}
            return render(request, 'pages/account.html', context)
        login(request, user)
        return HttpResponseRedirect('/')
    return render(request, 'pages/account.html', {})#update data for register_user

def register_user(request):
    form = RegisterForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            regis = form.save()
            regis.refresh_from_db()   # refresh data
            
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            email = form.cleaned_data["email"]
            user = authenticate(username=username, password=password, email=email)  #get username, password and check check them against each authentication backend
            login(request, user)
            return render(request, "pages/register_ss.html")
        else:
            form = RegisterForm(request.POST)
            return render(request, "pages/regis_err.html")
            
    return render(request, 'pages/resgister.html', {'form': form})



def logout_user(request):
    logout(request)
    return redirect('/')

social_network/newfeed/templates/pages/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Ice Crime</title>
    <link rel="icon" href="/media/favicon.ico" type="image/png" sizes="16x16"> 
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	<div class="container-fluid pdng0">
		<div class="row">
			<div class="col-lg-12">
				<div class="error-page">
					<div class="bg-image" style="background-image: url(/media/image/404.png)"></div>
					<div class="error-meta">
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
						<span>Vui lòng đăng nhập hoặc đăng kí</span>
                        <span>Để có thể đăng bài, xin cảm ơn!</span>
                        <a href="/user/login" title="" data-ripple="">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>	

</html>

social_network/newfeed/templates/pages/login_err.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Ice Crime</title>
    <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16"> 
    
    <link rel="stylesheet" href="{% load 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% load 'css/style.css' %}">
    <link rel="stylesheet" href="{% load 'css/color.css' %}">
    <link rel="stylesheet" href="{% load 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	<div class="container-fluid pdng0">
		<div class="row">
			<div class="col-lg-12">
				<div class="error-page">
					<div class="bg-image" style="background-image: url(images/resources/404.jpg)"></div>
					<div class="error-meta">
						<h1>whoops!</h1>
						<span>we couldn't find that page </span>
						<a href="index-2.html" title="" data-ripple="">Go Back</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
	<script src="js/main.min.js"></script>
	<script src="js/script.js"></script>

</body>	

</html>

social_network/newfeed/templates/pages/post.html
{% extends 'pages/base.html' %}
{% block title%}  {% endblock %}

{% block content %}

<div class="col-lg-6">
    <div class="loadMore">
        <div class="central-meta item">
            <div class="new-postbox">
                <figure>
                    <img src="images/resources/admin2.jpg" alt="">
                </figure>
                <div class="newpst-input">
                    <h1>CREATE POST</h1>
                    <form action="{% url "newfeed:savePost" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        {{ f.content }}
                        <div class="attachments" >
                            <ul>
                                <li> 
                                    <i class="fa fa-image"></i>
                                    <label class="fileContainer">
                                        {{ f.image }}
                                    </label>
                                </li>
                                <li>
                                    <button type="submit">Publish</button>
                                </li>
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- add post new box --> 
    </div>
</div>
{% endblock %}

social_network/newfeed/templates/pages/posts.html
{% extends 'pages/base.html' %}
{% block title%} ICE CREAM {% endblock %}

{% block content %}

{% for post in posts %}

<div class="col-lg-6">
    <!-- add post new box -->
    <div class="loadMore">

        <div class="central-meta item">
            <div class="new-postbox">
                <div class="newpst-input">
                    <a href="{% url "newfeed:newfeed" %}">
                        <h1>ICE CREAM 🍨</h1>
                    </a>
                </div>
            </div>
        </div>

        
        <div class="central-meta item">
            <div class="user-post">
                <div class="friend-info">
                    <figure>
                        <img src="/media/Ca.png" alt="">
                    </figure>
                    <div class="friend-name">
                        <ins><a class="username" href="time-line.html" title="">{{post.created_by}}</a></ins>
                        <span>{{post.time_create}}</span>
                    </div>
                    <div class="post-meta">
                        <p> {{post.content}} </P>
                        {% if post.image %}
                        <img src="{{ post.image.url}}" alt="">
                        {% else %}
                        <img src="" alt="">
                        {% endif %}
                        
                        <div class="description">
                            
                            <p>
                                
                            </p>
                        </div>
                        <div class="we-video-info">
                            <ul>
                                
                                <li>
                                    <span class="views" data-toggle="tooltip" title="views">
                                        <i class="fa fa-eye"></i>
                                        <ins>0</ins>
                                    </span>
                                </li>
                                <li>
                                    <span class="comment" data-toggle="tooltip" title="Comments">
                                        <i class="fa fa-comments-o"></i>
                                        <ins>0</ins>
                                    </span>
                                </li>
                                <li>
                                    <span class="like" data-toggle="tooltip" title="like">
                                        <i class="ti-heart"></i>
                                        <ins>0</ins>
                                    </span>
                                </li>
                                <li>
                                    <span class="dislike" data-toggle="tooltip" title="dislike">
                                        <i class="ti-heart-broken"></i>
                                        <ins>0</ins>
                                    </span>
                                </li>
                                <li class="social-media">
                                    <div class="menu">
                                      <div class="btn trigger"><i class="fa fa-share-alt"></i></div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-html5"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-facebook"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-google-plus"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-twitter"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-css3"></i></a></div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-instagram"></i></a>
                                        </div>
                                      </div>
                                        <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-dribbble"></i></a>
                                        </div>
                                      </div>
                                      <div class="rotater">
                                        <div class="btn btn-icon"><a href="#" title=""><i class="fa fa-pinterest"></i></a>
                                        </div>
                                      </div>

                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div class="coment-area">
                    {% for comment in form %}
                    <ul class="we-comet">
                        <li>
                            <div class="comet-avatar">
                                <img src="images/resources/comet-1.jpg" alt="">
                            </div>
                            <div class="we-comment">
                                <div class="coment-head">
                                    <h5><a href="time-line.html" title="">{{comment.user_name}}</a></h5>
                                    <span>{{comment.time_comment}}</span>
                                    <a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
                                </div>
                                <p>{{comment.user_comment}}</p>
                            </div>
                            <ul>
                                <li>
                                    <div class="comet-avatar">
                                        <img src="images/resources/comet-2.jpg" alt="">
                                    </div>
                                    <div class="we-comment">
                                        <div class="coment-head">
                                            <h5><a href="time-line.html" title="">Cá nè</a></h5>
                                            <span>1 hours ago</span>
                                            <a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
                                        </div>
                                        <p>Sủa <a href="#" title=""></a></p>
                                    </div>
                                </li>
                                <li>
                                    <div class="comet-avatar">
                                        <img src="images/resources/comet-3.jpg" alt="">
                                    </div>
                                    <div class="we-comment">
                                        <div class="coment-head">
                                            <h5><a href="time-line.html" title="">Olivia</a></h5>
                                            <span>16 days ago</span>
                                            <a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
                                        </div>
                                        <p>i like lexus cars, lexus cars are most beautiful with the awesome features, but this car is really outstanding than lexus</p>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <div class="comet-avatar">
                                <img src="images/resources/comet-1.jpg" alt="">
                            </div>
                            <div class="we-comment">
                                <div class="coment-head">
                                    <h5><a href="time-line.html" title="">Donald Trump</a></h5>
                                    <span>1 week ago</span>
                                    <a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
                                </div>
                                <p>we are working for the dance and sing songs. this video is very awesome for the youngster. please vote this video and like our channel
                                    <i class="em em-smiley"></i>
                                </p>
                            </div>
                        </li>
                        <li>
                            <a href="#" title="" class="showmore underline">more comments</a>
                        </li>
                        <li class="post-comment">
                            <div class="comet-avatar">
                                <img src="images/resources/comet-1.jpg" alt="">
                            </div>
                            <div class="post-comt-box">
                                <form method="POST">
                                    <textarea class="comment" placeholder="Post your comment"></textarea>
                                    <div class="add-smiles">
                                        <span class="em em-expressionless" title="add icon"></span>
                                    </div>
                                    <div class="smiles-bunch">
                                        <i class="em em---1"></i>
                                        <i class="em em-smiley"></i>
                                        <i class="em em-anguished"></i>
                                        <i class="em em-laughing"></i>
                                        <i class="em em-angry"></i>
                                        <i class="em em-astonished"></i>
                                        <i class="em em-blush"></i>
                                        <i class="em em-disappointed"></i>
                                        <i class="em em-worried"></i>
                                        <i class="em em-kissing_heart"></i>
                                        <i class="em em-rage"></i>
                                        <i class="em em-stuck_out_tongue"></i>
                                    </div>
                                    <button type="submit"></button>
                                </form>	
                            </div>
                        </li>
                    </ul>
                    {% endfor %}
                </div>
                
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

social_network/user/templates/pages/account.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <title>Ice Cream</title>
    <link rel="icon" href="/media/favicon.ico" type="image/png" sizes="16x16">

    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>

<body>
    <!--<div class="se-pre-con"></div>-->
    <div class="theme-layout">
        <div class="container-fluid pdng0">
            <div class="row merged">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="land-featurearea">
                        <div class="land-meta">
                            <h1>ICE CREAM</h1>
                            <p>
                                BUT NOT COLD!
                            </p>
                            <div class="friend-logo">
                                <span><img src="/media/wink.png" alt=""></span>
                            </div>
                            <a href="https://github.com/calangthang-wf" title="github" class="folow-me">Follow Me</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="login-reg-bg">
                        <div class="log-reg-area sign">
                            <h2 class="log-title">Login</h2>
                            <p>
                                Don’t use Ice Cream Yet? <a href="/" title="">Take the tour</a> or <a href="/login" title="">Join now</a>
                            </p>
                            {% if not request.user.is_authenticate %}
                            <form action='' method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input name="username" type="text" id="input" required="required" />
                                    <label class="control-label" for="input">Username</label><i class="mtrl-select"></i>
                                </div>
                                <div class="form-group">
                                    <input name="password" type="password" required="required" />
                                    <label class="control-label" for="input">Password</label><i class="mtrl-select"></i>
                                    <a>{{ error }}</a>
                                </div>
                                
                                <div class="checkbox">
                                    <label>
								        <input type="checkbox" checked="checked"/><i class="check-box"></i>Always Remember Me.
							        </label>
                                </div><br>
                                <a href="{% url "register_user" %}">Register</a>
                                <a href="#" title="" class="forgot-pwd">Forgot Password?</a>
                                <div class="submit-btns">
                                    <button class="mtr-btn signin" type="submit"><span>Login</span></button>
                                </div>
                            </form>
                            {% else %}
                            <p> You are already login, would you like <a href="/logout">logout?</a></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

social_network/user/templates/pages/ald_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Ice Crime</title>
    <link rel="icon" href="/media/favicon.ico" type="image/png" sizes="16x16"> 
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	<div class="container-fluid pdng0">
		<div class="row">
			<div class="col-lg-12">
				<div class="error-page">
					<div class="bg-image" style="background-image: url(/media/image/404.png)"></div>
					<div class="error-meta">
						<span>Đăng nhập thành công!</span>
                        <a href="{% url "home" %}" title="" data-ripple="">Back Home</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
	<script src="js/main.min.js"></script>
	<script src="js/script.js"></script>

</body>	

</html>

social_network/user/templates/pages/already_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Ice Crime</title>
    <link rel="icon" href="/media/favicon.ico" type="image/png" sizes="16x16"> 
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	<div class="container-fluid pdng0">
		<div class="row">
			<div class="col-lg-12">
				<div class="error-page">
					<div class="bg-image" style="background-image: url(/media/image/404.png)"></div>
					<div class="error-meta">
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
						<span>Có vẻ bạn muốn đăng xuất?</span>
						<a href="{% url "logout" %}" title="" data-ripple="">Đăng xuất</a>
                        <a href="/" title="" data-ripple="">Back Home</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
	<script src="js/main.min.js"></script>
	<script src="js/script.js"></script>

</body>	

</html>

social_network/user/templates/pages/register_ss.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Ice Crime</title>
    <link rel="icon" href="/media/favicon.ico" type="image/png" sizes="16x16"> 
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	<div class="container-fluid pdng0">
		<div class="row">
			<div class="col-lg-12">
				<div class="error-page">
					<div class="bg-image" style="background-image: url()"></div>
					<div class="error-meta">
						<span>Đăng kí thành công!</span>
                        <span>Chào mừng bạn đến với Ice Crime!</span>
                        <a href="/" title="" data-ripple="">Back Home</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
	<script src="js/main.min.js"></script>
	<script src="js/script.js"></script>

</body>	

</html>